name: Ubuntu 16.04 base
run-name: Build and push the Ubuntu 16.04 base

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  ubuntu-1604:
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:ubuntu_1604"
          push: true
          tags: andrewdavidsmith/ubuntu-1604:latest
          # Enable SBOM + provenance attestations
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          # Provenance (SLSA) + SBOM
          provenance: true
          sbom: true
      # - name: Generate SBOM attestation
      - name: Dump GitHub Actions contexts
        run: |
          echo '=== github ==='
          echo '${{ toJson(github) }}'

          echo '=== env ==='
          echo '${{ toJson(env) }}'

          echo '=== job ==='
          echo '${{ toJson(job) }}'

          echo '=== steps ==='
          echo '${{ toJson(steps) }}'

          echo '=== runner ==='
          echo '${{ toJson(runner) }}'

          echo '=== matrix ==='
          echo '${{ toJson(matrix) }}'

          echo '=== inputs ==='
          echo '${{ toJson(inputs) }}'

          echo '=== outputs ==='
          echo '${{ toJson(outputs) }}'
        # uses: actions/attest-sbom@v2
        # with:
        #   subject-name: ${{ env.REGISTRY }}/andrewdavidsmith/ubuntu-1604
        #   subject-digest: ${{ outputs.digest }}
        #   sbom-path: "sbom.json"
        #   push-to-registry: true
